name: alifi
description: "Alifi - All-in-one platform for pet owners"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.8
  rush:
    git:
      url: https://github.com/khaledSayedAbdellah/rush
      ref: "2ff9fce"
  go_router: ^7.1.1
  provider: ^6.0.5
  flutter_screenutil: ^5.7.0
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.5
  photo_view: ^0.14.0

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10

  # Maps & Location
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # Image & Media
  image_picker: ^1.0.7
  cached_network_image: ^3.3.0
  file_picker: ^8.0.0+1

  # State Management & Utilities
  get_it: ^7.6.0
  shared_preferences: ^2.1.1
  state_extended: ^5.5.0
  equatable: ^2.0.5
  dartz: ^0.10.1

  # HTTP & Network
  fast_http: ^1.0.6
  http: ^1.0.0
  internet_connection_checker_plus: ^2.0.0

  # Internationalization
  intl: ^0.20.2

  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - i18n/
    - assets/
    - assets/icons/
    - assets/images/
    - assets/animations/
