// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrzOlXjtKLa-xsY--c3ijkMbejVJcGIwM',
    appId: '1:470661629842:web:acba6cbfd1a488abc3e34b',
    messagingSenderId: '470661629842',
    projectId: 'bookingplayground-3f74b',
    authDomain: 'bookingplayground-3f74b.firebaseapp.com',
    storageBucket: 'bookingplayground-3f74b.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrzOlXjtKLa-xsY--c3ijkMbejVJcGIwM',
    appId: '1:470661629842:android:acba6cbfd1a488abc3e34b',
    messagingSenderId: '470661629842',
    projectId: 'bookingplayground-3f74b',
    storageBucket: 'bookingplayground-3f74b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrzOlXjtKLa-xsY--c3ijkMbejVJcGIwM',
    appId: '1:470661629842:ios:acba6cbfd1a488abc3e34b',
    messagingSenderId: '470661629842',
    projectId: 'bookingplayground-3f74b',
    storageBucket: 'bookingplayground-3f74b.appspot.com',
    iosBundleId: 'com.example.template2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrzOlXjtKLa-xsY--c3ijkMbejVJcGIwM',
    appId: '1:470661629842:ios:acba6cbfd1a488abc3e34b',
    messagingSenderId: '470661629842',
    projectId: 'bookingplayground-3f74b',
    storageBucket: 'bookingplayground-3f74b.appspot.com',
    iosBundleId: 'com.example.template2025',
  );
} 